#!/usr/bin/env node
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";

const rl = createInterface({ input, output });

async function ask(label, fallback) {
  const suffix = fallback ? ` [${fallback}]` : "";
  const answer = (await rl.question(`${label}${suffix}: `)).trim();
  return answer || fallback || "";
}

console.log("\n🧭 solana-indexer setup wizard\n");

if (existsSync(".env")) {
  const overwrite = await ask("⚠️  .env already exists. Overwrite? (y/N)", "N");
  if (overwrite.toLowerCase() !== "y") {
    console.log("Aborted. Existing .env kept.");
    rl.close();
    process.exit(0);
  }
}

const DATABASE_URL = await ask("Postgres URL", "postgres://indexer:indexer@localhost:5432/indexer");
const RPC_URL = await ask("Solana RPC URL (Helius recommended)", "https://mainnet.helius-rpc.com/?api-key=YOUR_HELIUS_KEY");
let WEBHOOK_AUTH_HEADER = await ask("Webhook auth secret (blank = generate)", "");
if (!WEBHOOK_AUTH_HEADER) {
  WEBHOOK_AUTH_HEADER = randomBytes(24).toString("hex");
  console.log(`   → generated: ${WEBHOOK_AUTH_HEADER}`);
}
const PORT = await ask("Webhook port", "8080");
const API_PORT = await ask("API port", "8090");

const lines = [
  "# Generated by `npm run init`",
  `DATABASE_URL=${DATABASE_URL}`,
  `RPC_URL=${RPC_URL}`,
  `WEBHOOK_AUTH_HEADER=${WEBHOOK_AUTH_HEADER}`,
  `PORT=${PORT}`,
  `API_PORT=${API_PORT}`,
  "",
];
writeFileSync(".env", lines.join("\n"));
console.log("\n✅ Wrote .env. Next: docker compose up -d && npm run migrate && npm run doctor\n");
rl.close();
